Revert "Drop nxp Android.bp"
error: vendor/nxp/opensource/sn100x/halimpl/SN100x/halimpl/libnxpparser: MODULE.TARGET.SHARED_LIBRARIES.nxp_nci_parser already defined by hardware/nxp/nfc/snxxx/halimpl/libnxpparser when using vendor/nxp/opensource

This reverts commit 5c8401ad1b3d28fad12898b96712b7997b126a86.

Change-Id: I6fc5b45a22e59e2ee84a3baa0912cdd5da4de04d